### PR TITLE
Add !nice command

### PR DESCRIPTION
**Pull request by kshannoninnes**

### CODE REVIEW

**Comment by lukasni** [comment]
I'd prefer having the "set personality to <userid>" part more generalized, maybe as a `Slack.set_personality(user_id: str)` function in slack.py. Thoughts?

**Comment by kshannoninnes** [comment]
Can do, but that would only work for setting the personality to actual users, not faux-users like "Malbot". If you foresee this kind of feature being used often in the future, it would definitely be more modular.

**Comment by lukasni** [comment]
Mainly for joke commands like this, but I think having the option would be good.

**Comment by kshannoninnes** [comment]
Modularized set_personality and refactored nice command to adjust

**Pull request merged**
